baseURL = "https://gwangyi.github.io/"
title = "Worldwide gwangyi"
theme = ["mdi", "etch"]
languageCode = "ko-KR"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "To be survived wordwidely"
  copyright = "Copyright © 2018-2023 Sungkwang Lee"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    title = "tags"
    url = "/tags/"
    weight = 11

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:section/:filename"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true

[markup.highlight]
  lineNos = true

[taxonomies]
  series = "series"
  tag = "tags"
